name: CI/CD Pipeline - Static Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      APP_ENV_MESSAGE: ${{ secrets.APP_ENV_MESSAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Build info (secret auto-mask in logs)
        run: |
          echo "Building Static Sites ...."
          echo "Build tag message: $APP_ENV_MESSAGE"
          ls -la

      - name: Upload site as pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test Suite
        run: bash test.sh 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  notify:
    name: notify
    runs-on: ubuntu-latest
    needs: deploy
    env: 
      WEBHOOK: ${{ secrets.DEPLOY_WEBHOOK }}
    steps:
      - name: Send deployement notification
        run: |
          echo "deployment finished"
          echo "Notifying monitoring endpoint (URL masked): $WEBHOOK"
          curl -s -o /dev/null -w "Webhook respond with status: %{http_code}\n" "$WEBHOOK" || true
